FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy shared library
COPY ./shared ./shared

# Copy gateway script
COPY ./api_gateway.py .

EXPOSE 8000

CMD ["python", "api_gateway.py"]
